[package]
name = "fullstack"
version = "0.0.1"
edition = "2021"
authors = ["ivanjericevich96@gmail.com"]
description = "A crate for the management of a postgresql database and the versions thereof using an asynchronous ORM"
readme = "README.md"
keywords = [""]
publish = false

[workspace]
members = [".", "api", "database"]

[dependencies]
api = { path = "api" }
