[package]
name = "rusty-exchange"
version = "0.0.0"
edition = "2021"
authors = ["ivanjericevich96@gmail.com"]
description = "A workspace for a fullstack app written entirely in Rust"
readme = "README.md"
keywords = [""]
publish = false

[workspace]
members = [".", "api", "database", "orderbook"]

[dependencies]
api = { path = "api" }
orderbook = { path = "orderbook" }
async-std = { version = "^1", features = ["attributes", "tokio1"] } # Standard async library

[[bin]]
name = "api"
path = "src/bin/api.rs"

[[bin]]
name = "matching_engine"
path = "src/bin/matching_engine.rs"
