[package]
name = "fullstack-rs"
version = "0.0.0"
edition = "2021"
authors = ["ivanjericevich96@gmail.com"]
description = "A workspace for a fullstack app written entirely in Rust"
readme = "README.md"
keywords = [""]
publish = false

[workspace]
members = [".", "api", "database", "rabbitmq"]

[dependencies]
api = { path = "api" }
