version: '3'

volumes:
  postgres:
  rabbitmq:
  pgadmin:

networks:
  rabbitmq:
    driver: bridge
  postgres:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:management  # arm64v8/  add this to beginning if on m1 mac
    container_name: rabbitmq_container
    ports:
      - '5672:5672'
      - '5552:5552'
      - '15672:15672'
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq
      - $PWD/rmq_enabled_plugins:/etc/rabbitmq/enabled_plugins # Enable stream plugin
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_stream advertised_host localhost
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-Exchange}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
  api:
    container_name: api_container
    image: api
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-Exchange}
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8080:8080"
  matching_engine:
    container_name: matching_engine_container
    image: matching_engine
    build:
      context: .
      dockerfile: ./orderbook/Dockerfile