version: '3'

volumes:
  postgres_data_dev: {}
  rabbitmq_data_dev: {}

networks:
  rabbitmq_go_net:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine  # arm64v8/  add this to beginning if on m1 mac
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq/
      - rabbitmq_data_dev:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net