name: Test

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.idea'
      - '.dockerignore'
      - '.gitignore'
      - 'LICENSE'
      - 'docker-compose.yaml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.idea'
      - '.dockerignore'
      - '.gitignore'
      - 'LICENSE'
      - 'docker-compose.yaml'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --workspace --exclude api --features mock
